{
 "title": "ACaaD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_server_active_requests,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_active_requests{job=\"$job\"},instance)"
    }
   },
   {
    "name": "acaadName",
    "label": "Server Name",
    "query": {
     "query": "label_values(acaad_target_info{job=\"$job\"},acaad_name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Component Metrics: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Avg. Command Duration by Component",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(acaad_core_command_execution_duration_seconds_sum{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]) / rate(acaad_core_command_execution_duration_seconds_count{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "Avg. Transformation Duration by Component",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(acaad_core_transformation_execution_duration_seconds_sum{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]) / rate(acaad_core_transformation_execution_duration_seconds_count{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "Command Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(acaad_core_command_execution_duration_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(acaad_core_command_execution_duration_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(acaad_core_command_execution_duration_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(acaad_core_command_execution_duration_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(acaad_core_command_execution_duration_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(acaad_core_command_execution_duration_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(acaad_core_command_execution_duration_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Failing Components",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, increase(acaad_processing_component_failed_total{job=\"$job\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Schedule to Execution Delay",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "acaad_processing_scheduling_delay_milliseconds_sum{job=\"$job\", instance=~\"$instance\"} / acaad_processing_scheduling_delay_milliseconds_count{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Scheduling Delay"
    }
   ]
  },
  {
   "title": "Avg. Transformation TreeGen Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(acaad_processing_parser_parse_tree_generation_duration_milliseconds_sum{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]) / rate(acaad_processing_parser_parse_tree_generation_duration_milliseconds_count{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{transformation_hint}}"
    }
   ]
  },
  {
   "title": "Cached Parse Trees",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(acaad_processing_parser_transformations_cached_total{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors By Host",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by(instance) (rate({level=\"ERROR\"} [$__auto]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg. Schedule to Execution Delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "acaad_processing_scheduling_delay_milliseconds_sum{job=\"$job\", instance=~\"$instance\"} / acaad_processing_scheduling_delay_milliseconds_count{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Scheduling Delay"
    }
   ]
  },
  {
   "title": "Resource Consumption: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "instance"
  },
  {
   "title": "Generation Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "dotnet_gc_last_collection_heap_size_bytes{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{gc_heap_generation}}"
    }
   ]
  },
  {
   "title": "Overall Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "dotnet_process_memory_working_set_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Working Set"
    },
    {
     "expr": "dotnet_gc_last_collection_memory_committed_size_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Committed Size"
    },
    {
     "expr": "dotnet_jit_compiled_il_size_bytes_total{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Compiled IL"
    },
    {
     "expr": "sum(dotnet_gc_last_collection_heap_size_bytes{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "GC Summed"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rate(dotnet_process_cpu_time_seconds_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{cpu_mode}}"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "rate(dotnet_gc_pause_time_seconds_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}