{
 "title": "ACaaD Host",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(system_cpu_logical_count,host_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host: $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{host_name=~\"$host\", state=\"cached\", service_namespace=\"agent\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "system_memory_usage_bytes{host_name=~\"$host\", state=\"buffered\", service_namespace=\"agent\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "system_memory_usage_bytes{host_name=~\"$host\", state=\"used\", service_namespace=\"agent\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "system_memory_usage_bytes{host_name=~\"$host\", state=\"free\", service_namespace=\"agent\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (state) (rate(system_cpu_time_seconds_total{host_name=~\"$host\", state!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(3, rate(system_network_io_bytes_total{host_name=~\"$host\", device!~\"docker.*\"}[$__rate_interval])) > 0",
     "legendFormat": "{{direction}}: {{device}}"
    },
    {
     "expr": "topk(3, sum by (direction) (rate(system_network_io_bytes_total{host_name=~\"$host\", device=~\"docker.*\"}[$__rate_interval]))) > 0",
     "legendFormat": "{{direction}}: All DKRs"
    }
   ]
  }
 ]
}